### ISSUE TITLE
Extra forward slashes creating invalid URLs in returned content.

### ISSUE THREAD

**Issue by ahjwang** [jina-ai/reader#144] opened 2024-10-08 20:11 UTC
Hello, thank you for the useful tool. The reader seems to be adding an extra `/` in front of parentheses `()` in the URLs of the returned markdown, causing the URLs to become invalid. Here is an example HTML:

```html
<html>
<head>
    <title>Test</title>
</head>
<body>
    <h1>Links</h1>
    <p>Links have an extra forward slash in front of parentheses.</p>
    <!-- This becomes "https://www.example.com/test_/(something/)" -->
    <a href="https://www.example.com/test_(url)" title="Failing">Failing</a>
    <p>Image src links are somehow ok, but the links are also not right.</p>
    <!-- This becomes "https://www.example.com/test_/(url/)" but img_src is ok -->
    <a href="https://www.example.com/test_(url)">
        <img src="https://www.example.com/images/some_(image).png" alt="Google">
    </a>
</body>
</html>
```

When I run this through the Reader API online, I get the following output:
```markdown
Title: Test

URL Source: https://example.com/

Markdown Content:
Links
-----

Links have an extra forward slash in front of parentheses.

[Failing](https://www.example.com/test_/(url/) "Failing")Image src links are somehow ok, but the links are also not right.

[![Image 1: Google](https://www.example.com/images/some_(image).png)](https://www.example.com/test_/(url/))
```

Since there are parentheses in many URLs, e.g. "https://en.wikipedia.org/wiki/Ford_(crossing)", this is causing a lot of links to become invalid. This appears to be a problem that is affecting both the reader and search tools. Many thanks in advance for looking into this!

**Comment by nomagick** [comment] 2024-10-18 08:09
Indeed a bug caused by markdown escaption and later transformation to a valid URL.
Sorry for the inconvenience.

Fixed in https://github.com/jina-ai/reader/commit/74eac2fc1809fab4bd8b97d441f57bdfe145f14f

Thanks for reporting this to us.

**Closed by nomagick** 2024-10-18 08:09 UTC
